services:
  - type: web
    name: sabi-biz-backend
    env: node
    region: oregon
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: bash run.sh
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
