ALTER TABLE customers
  ADD COLUMN IF NOT EXISTS city VARCHAR(100),
  ADD COLUMN IF NOT EXISTS region VARCHAR(100),
  ADD COLUMN IF NOT EXISTS delivery_address TEXT,
  ADD COLUMN IF NOT EXISTS birthday DATE,
  ADD COLUMN IF NOT EXISTS anniversary DATE,
  ADD COLUMN IF NOT EXISTS auto_birthday BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS auto_anniversary BOOLEAN DEFAULT FALSE;
